services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: serviceops
      POSTGRES_PASSWORD: serviceops
      POSTGRES_DB: serviceops_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U serviceops -d serviceops_db"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: 